export * from './pure/graph'

export { type RecentNodeHistory, MAX_RECENT_NODES, extractRecentNodesFromDelta, addEntriesToHistory, removeNodeFromHistory, updateHistoryFromDelta, createEmptyHistory } from './pure/graph/recentNodeHistoryV2'
export { fromCreateChildToUpsertNode, createNewNodeNoParent, generateChildNodeId, fromContentChangeToGraphDelta, createDeleteNodesAction } from './pure/graph/graphDelta/uiInteractionsToGraphDeltas'
export { createTaskNode, type TaskNodeCreationParams } from './pure/graph/graph-operations/createTaskNode'
export { findFirstParentNode } from './pure/graph/graph-operations/findFirstParentNode'
export { computeExtractIntoFolderGraphDelta, getExtractIntoFolderSelectionSupport, type ExtractIntoFolderSelectionSupport, type ComputeExtractIntoFolderGraphDeltaResult } from './pure/graph/graph-operations/extract-into-folder/computeExtractIntoFolderGraphDelta'
export { computeMergeGraphDelta } from './pure/graph/graph-operations/merge/computeMergeGraphDelta'
export { type IncomingEdgesIndex, buildIncomingEdgesIndex, updateIndexForUpsert, updateIndexForDelete } from './pure/graph/graph-operations/incomingEdgesIndex'
export { reverseDelta } from './pure/graph/undo/reverseDelta'
export { createEmptyUndoState, pushUndo, popUndo, popRedo, MAX_UNDO_SIZE, type UndoState } from './pure/graph/undo/undoStack'
export { VIDEO_EXTENSIONS, isVideoNode } from './pure/graph/isVideoNode'
export { CIRCLE_SIZE } from './pure/graph/node-presentation/types'
export { ensureUniqueNodeId } from './pure/graph/ensureUniqueNodeId'
export { addNodeToGraphWithEdgeHealingFromFSEvent } from './pure/graph/graphDelta/addNodeToGraphWithEdgeHealingFromFSEvent'
export { getFolderChildNodeIds } from './pure/graph/folderCollapse'
export { hasActualContentChanged, isAppendOnly, getAppendedSuffix, stripBracketedContent } from './pure/graph/contentChangeDetection'
export type { DirectoryEntry } from './pure/folders/transforms'
