export { GraphDbClient } from './GraphDbClient.ts'
export {
  DaemonLaunchTimeout,
  DaemonUnreachableError,
  GraphDbClientError,
} from './errors.ts'
export { readPortFile, discoverPort } from './portDiscovery.ts'
export {
  ensureDaemon,
  killOrphanVtGraphdDaemons,
  type EnsureDaemonResult,
  type OrphanCleanupResult,
} from './autoLaunch.ts'
export {
  createContextNode,
  createContextNodeFromQuestion,
  createContextNodeFromSelection,
  getUnseenNodesNearby,
  updateContextNodeContainedIds,
  getPreviewContainedNodeIds,
} from './contextNodeClient.ts'
export { buildSearchIndex, search, findFileByName } from './searchClient.ts'
export { getProjectRoot, setProjectRoot, getWatchStatus } from './watchClient.ts'

export {
  CONTRACT_VERSION,
  AddReadPathRequestSchema,
  BuildIndexRequestSchema,
  CollapseStateResponseSchema,
  CreateContextNodeFromQuestionRequestSchema,
  CreateContextNodeFromSelectionRequestSchema,
  CreateContextNodeRequestSchema,
  CreateContextNodeResponseSchema,
  FindFileResponseSchema,
  GraphStateSchema,
  HealthResponseSchema,
  LayoutPartialSchema,
  LayoutResponseSchema,
  LiveStateSnapshotSchema,
  LoadAndMergeRequestSchema,
  LoadAndMergeResponseSchema,
  NodeSearchHitSchema,
  PreviewContainedNodeIdsResponseSchema,
  ProjectRootResponseSchema,
  RedoResponseSchema,
  SearchResponseSchema,
  SelectionModeSchema,
  SelectionRequestSchema,
  SelectionResponseSchema,
  SessionCreateResponseSchema,
  SessionInfoSchema,
  SetProjectRootRequestSchema,
  SetWritePathRequestSchema,
  ShutdownResponseSchema,
  UndoResponseSchema,
  UnseenNodeSchema,
  UnseenNodesResponseSchema,
  UpdateContainedIdsRequestSchema,
  VaultStateSchema,
  ViewResponseSchema,
  WatchStatusResponseSchema,
  WritePositionsResponseSchema,
  type AddReadPathRequest,
  type BuildIndexRequest,
  type CollapseStateResponse,
  type CreateContextNodeFromQuestionRequest,
  type CreateContextNodeFromSelectionRequest,
  type CreateContextNodeRequest,
  type CreateContextNodeResponse,
  type FindFileResponse,
  type GraphState,
  type HealthResponse,
  type LayoutPartial,
  type LayoutResponse,
  type LiveStateSnapshot,
  type LoadAndMergeRequest,
  type LoadAndMergeResponse,
  type NodeSearchHit,
  type PreviewContainedNodeIdsResponse,
  type ProjectRootResponse,
  type RedoResponse,
  type SearchResponse,
  type SelectionMode,
  type SelectionRequest,
  type SelectionResponse,
  type SessionCreateResponse,
  type SessionInfo,
  type SetProjectRootRequest,
  type SetWritePathRequest,
  type ShutdownResponse,
  type UndoResponse,
  type UnseenNode,
  type UnseenNodesResponse,
  type UpdateContainedIdsRequest,
  type VaultState,
  type ViewResponse,
  type WatchStatusResponse,
  type WritePositionsResponse,
} from '@vt/graph-db-server/contract'
