// Pure formatter: WorkflowYaml → text. Kept separate from gen-workflows.ts
// so the discovery/transform shell stays small and the renderer can grow
// independently when new Step kinds are added.

import type {Job, Step, WorkflowYaml} from './_types.ts'

const HEADER = [
    '# AUTO-GENERATED by packages/measures/scripts/gen-workflows.ts',
    '# from tier_N/_workflow.ts. Do not edit by hand.',
    '# Run `pnpm run gen:workflows` to regenerate.',
    '# Required GitHub contexts are derived from tier WorkflowSpec.protection.',
].join('\n')

const PNPM_VERSION = '10.32.1'

export function workflowYamlToText(yaml: WorkflowYaml): string {
    const lines: string[] = []
    lines.push(HEADER)
    lines.push(`name: ${yamlString(yaml.name)}`)
    lines.push('')
    lines.push('on:')
    lines.push('  workflow_dispatch: {}')
    lines.push('  pull_request:')
    lines.push('')
    lines.push('jobs:')
    for (const job of yaml.jobs) {
        lines.push(...renderJob(job))
        lines.push('')
    }
    return lines.join('\n').replace(/\n+$/, '\n')
}

function renderJob(job: Job): readonly string[] {
    const lines: string[] = []
    lines.push(`  ${job.id}:`)
    lines.push(`    name: ${yamlString(job.name)}`)
    if (job.needs.length > 0) {
        lines.push(`    needs: [${job.needs.join(', ')}]`)
    }
    if (job.ifExpr !== null) {
        lines.push(`    if: ${yamlString(job.ifExpr)}`)
    }
    lines.push(`    runs-on: ${job.runsOn}`)
    if (job.strategy) {
        lines.push('    strategy:')
        lines.push('      fail-fast: false')
        lines.push('      matrix:')
        lines.push('        check_id:')
        for (const id of job.strategy.matrix.check_id) {
            lines.push(`          - ${id}`)
        }
    }
    if (job.outputs) {
        lines.push('    outputs:')
        for (const [key, value] of Object.entries(job.outputs).sort(([a], [b]) => a.localeCompare(b))) {
            lines.push(`      ${key}: ${yamlString(value)}`)
        }
    }
    lines.push('    steps:')
    for (const step of job.steps) {
        lines.push(...renderStep(step).map(l => l === '' ? '' : `      ${l}`))
    }
    return lines
}

function renderStep(step: Step): readonly string[] {
    switch (step.kind) {
        case 'checkout': return ['- uses: actions/checkout@v4']
        case 'pnpm-setup': return [
            '- uses: pnpm/action-setup@v4',
            '  with:',
            `    version: ${PNPM_VERSION}`,
        ]
        case 'setup-node': return [
            '- uses: actions/setup-node@v4',
            '  with:',
            `    node-version: '${step.node}'`,
            "    cache: 'pnpm'",
            '    cache-dependency-path: pnpm-lock.yaml',
        ]
        case 'install-deps': return [
            '- name: Install dependencies',
            '  env:',
            '    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}',
            '  run: pnpm install --frozen-lockfile',
        ]
        case 'playwright-install': return [
            '- name: Install Playwright chromium',
            '  working-directory: webapp',
            '  run: pnpm exec playwright install --with-deps chromium',
        ]
        case 'run': return renderRun(step.name, step.run, step.id ?? null, step.env ?? null)
        case 'upload-artifact': return [
            '- name: Upload check reports',
            '  if: always()',
            '  uses: actions/upload-artifact@v4',
            '  with:',
            `    name: ${step.name}`,
            `    path: ${step.path}`,
            '    retention-days: 1',
        ]
        case 'download-artifact': return [
            '- name: Download all check reports',
            '  uses: actions/download-artifact@v4',
            '  with:',
            `    pattern: ${step.pattern}`,
            `    path: ${step.path}`,
            '    merge-multiple: true',
        ]
    }
}

function renderRun(name: string, body: string, id: string | null, env: Record<string, string> | null): readonly string[] {
    const out: string[] = [`- name: ${yamlString(name)}`]
    if (id) out.push(`  id: ${id}`)
    if (env && Object.keys(env).length > 0) {
        out.push('  env:')
        for (const [key, value] of Object.entries(env).sort(([a], [b]) => a.localeCompare(b))) {
            out.push(`    ${key}: ${yamlString(value)}`)
        }
    }
    out.push('  run: |')
    for (const line of body.split('\n')) {
        const rendered = line.trimEnd()
        out.push(rendered === '' ? '' : `    ${rendered}`)
    }
    return out
}

function yamlString(s: string): string {
    if (/^[A-Za-z0-9_\-./]+$/.test(s)) return s
    return `"${s.replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`
}
