import type {CytoscapeCouplingAuditReport} from './cytoscapeCouplingAudit'
import {type AuditLocation, sortLocations} from './cytoscapeAuditLocationResolver'

function escapeTableCell(value: string): string {
    return value.replace(/\|/g, '\\|')
}

function groupLocationsByFile(locations: readonly AuditLocation[]): ReadonlyMap<string, readonly AuditLocation[]> {
    const grouped: Map<string, AuditLocation[]> = new Map()
    for (const location of locations) {
        const bucket: AuditLocation[] = grouped.get(location.relativePath) ?? []
        bucket.push(location)
        grouped.set(location.relativePath, bucket)
    }
    const sortedEntries: [string, readonly AuditLocation[]][] = [...grouped.entries()]
        .sort(([leftPath], [rightPath]) => leftPath.localeCompare(rightPath))
        .map(([relativePath, bucket]) => [relativePath, sortLocations(bucket)])
    return new Map(sortedEntries)
}

function formatLocationLink(location: AuditLocation): string {
    return `[${location.relativePath}:${location.lineNumber}](<${location.absolutePath}:${location.lineNumber}>)`
}

export function renderCytoscapeCouplingCatalogue(report: CytoscapeCouplingAuditReport): string {
    const lines: string[] = []
    const groupedOutsideProjectionLocations: ReadonlyMap<string, readonly AuditLocation[]> =
        groupLocationsByFile(report.outsideProjectionSeamLocations)

    lines.push('# Cytoscape Coupling Catalogue')
    lines.push('')
    lines.push('Generated by `npx tsx packages/graph-tools/scripts/audit-cytoscape-coupling.ts --write-catalogue`.')
    lines.push('')
    lines.push('## Baseline')
    lines.push(`- Outside projection seam \`cy.*\` count: ${report.outsideProjectionSeamCount}`)
    lines.push(`- Catalogue path: \`${report.catalogueRelativePath}\``)
    lines.push(`- Named surfaces audited: ${report.requiredSurfaces.join(', ')}`)
    lines.push(`- Additional surfaces flagged: ${report.additionalSurfaces.join(', ')}`)
    lines.push('')
    lines.push('## Projection Seam')
    for (const seamPattern of report.projectionSeamPatterns) {
        lines.push(`- \`${seamPattern}\``)
    }
    lines.push('')
    lines.push('## Cytoscape Imports By Package')
    lines.push('| Package | Count | Locations |')
    lines.push('| --- | ---: | --- |')
    for (const packageImportCount of report.packageImportCounts) {
        const renderedLocations: string = packageImportCount.locations.length === 0
            ? 'none'
            : packageImportCount.locations.map(formatLocationLink).join('<br>')
        lines.push(
            `| ${escapeTableCell(packageImportCount.packageName)} | ${packageImportCount.count} | ${renderedLocations} |`
        )
    }
    lines.push('')
    lines.push('## Outside Projection Seam `cy.*` Inventory')
    for (const [relativePath, locations] of groupedOutsideProjectionLocations.entries()) {
        lines.push(`### \`${relativePath}\` (${locations.length})`)
        for (const location of locations) {
            lines.push(`- ${formatLocationLink(location)} - \`${location.snippet}\``)
        }
        lines.push('')
    }
    lines.push('## Surface Catalogue')
    lines.push('| Surface | Reference | Current owner | Current consumer(s) | Mutates graph-model? | Survives restart? | Notes |')
    lines.push('| --- | --- | --- | --- | --- | --- | --- |')
    for (const surfaceEntry of report.surfaceEntries) {
        const renderedConsumers: string = surfaceEntry.consumers
            .map(consumer => `${escapeTableCell(consumer.description)} (${formatLocationLink(consumer.location)})`)
            .join('<br>')
        lines.push(
            `| ${escapeTableCell(`${surfaceEntry.surface}: ${surfaceEntry.label}`)} | ${formatLocationLink(surfaceEntry.primary)} | ${escapeTableCell(surfaceEntry.owner)} | ${renderedConsumers} | ${escapeTableCell(surfaceEntry.mutatesGraphModel)} | ${escapeTableCell(surfaceEntry.survivesRestart)} | ${escapeTableCell(surfaceEntry.notes)} |`
        )
    }
    return lines.join('\n').trimEnd() + '\n'
}

export function renderCytoscapeCouplingAuditSummary(report: CytoscapeCouplingAuditReport): string {
    const lines: string[] = []
    lines.push(`Outside projection seam count: ${report.outsideProjectionSeamCount}`)
    lines.push(`Catalogue: ${report.catalogueAbsolutePath}`)
    lines.push('Projection seam:')
    for (const seamPattern of report.projectionSeamPatterns) {
        lines.push(`- ${seamPattern}`)
    }
    lines.push('Cytoscape imports by package:')
    for (const packageImportCount of report.packageImportCounts) {
        lines.push(`- ${packageImportCount.packageName}: ${packageImportCount.count}`)
    }
    lines.push('Named surfaces:')
    for (const surface of report.requiredSurfaces) {
        lines.push(`- ${surface}`)
    }
    lines.push('Additional surfaces:')
    for (const surface of report.additionalSurfaces) {
        lines.push(`- ${surface}`)
    }
    lines.push('Outside projection seam callsites:')
    for (const location of report.outsideProjectionSeamLocations) {
        lines.push(`- ${location.relativePath}:${location.lineNumber} ${location.snippet}`)
    }
    return lines.join('\n')
}
